services:

  database:
    build:
      context: .
      dockerfile: db.dockerfile
    image: "wdai_db"
    container_name: database
    environment:
      POSTGRES_DB: wdai
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    restart: unless-stopped

  backend:
    image: golang:1.21
    volumes:
      - "./backend:/backend"
    working_dir: /backend
    container_name: backend
    depends_on:
      - database
    ports:
      - "4444:4444"
    restart: unless-stopped
    command: make run
