CREATE TYPE user_role AS ENUM ('user', 'admin');

CREATE TABLE "users" (
  "created_at" timestamp DEFAULT NOW(),
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(30) UNIQUE NOT NULL,
  "discord_username" varchar UNIQUE,
  "password_hash" varchar NOT NULL,
  "role" user_role DEFAULT 'user' NOT NULL
);

CREATE TABLE "skills" (
  "skill" varchar UNIQUE PRIMARY KEY
);

CREATE TABLE "skill_categories" (
  "skill" varchar NOT NULL,
  "category" varchar NOT NULL
);

CREATE TABLE "categories" (
  "category" varchar UNIQUE PRIMARY KEY
);

CREATE TABLE "offers" (
  "created_at" timestamp DEFAULT NOW(),
  "offer_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "skill" varchar NOT NULL,
  "description" varchar NOT NULL
);

CREATE TABLE "reports" (
  "created_at" timestamp DEFAULT NOW(),
  "report_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reporting_user_id" int NOT NULL,
  "reported_offer_id" int,
  "reason" varchar NOT NULL,
  "description" varchar NOT NULL,
  "status" varchar NOT NULL
);

CREATE TABLE "report_reasons" (
  "reason" varchar UNIQUE PRIMARY KEY
);

CREATE TABLE "reviews" (
  "created_at" timestamp DEFAULT NOW(),
  "review_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reviewing_user_id" int NOT NULL,
  "reviewed_user_id" int NOT NULL,
  "star_count" int NOT NULL CHECK (star_count >= 0 AND star_count <= 5),
  "review" text NOT NULL
);

ALTER TABLE "skill_categories" ADD FOREIGN KEY ("skill") REFERENCES "skills" ("skill");

ALTER TABLE "skill_categories" ADD FOREIGN KEY ("category") REFERENCES "categories" ("category");

ALTER TABLE "offers" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "offers" ADD FOREIGN KEY ("skill") REFERENCES "skills" ("skill");

ALTER TABLE "reports" ADD FOREIGN KEY ("reporting_user_id") REFERENCES "users" ("user_id");

ALTER TABLE "reports" ADD FOREIGN KEY ("reported_user_id") REFERENCES "users" ("user_id");

ALTER TABLE "reports" ADD FOREIGN KEY ("reported_offer_id") REFERENCES "offers" ("offer_id");

ALTER TABLE "reports" ADD FOREIGN KEY ("reason") REFERENCES "report_reasons" ("reason");

ALTER TABLE "reviews" ADD FOREIGN KEY ("reviewing_user_id") REFERENCES "users" ("user_id");

ALTER TABLE "reviews" ADD FOREIGN KEY ("reviewed_user_id") REFERENCES "users" ("user_id");
