// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Admin struct {
	UserID pgtype.Int4
}

type Category struct {
	Category string
}

type Offer struct {
	CreatedAt   pgtype.Timestamp
	OfferID     int32
	UserID      int32
	Skill       string
	Description string
}

type Report struct {
	CreatedAt       pgtype.Timestamp
	ReportID        int32
	ReportingUserID int32
	ReportedUserID  pgtype.Int4
	ReportedOfferID pgtype.Int4
	Reason          string
	Description     string
	Status          string
}

type ReportReason struct {
	Reason string
}

type Review struct {
	CreatedAt       pgtype.Timestamp
	ReviewID        int32
	ReviewingUserID int32
	ReviewedUserID  int32
	StarCount       int32
	Review          string
}

type Skill struct {
	Skill string
}

type SkillCategory struct {
	Skill    string
	Category string
}

type User struct {
	CreatedAt       pgtype.Timestamp
	UserID          int32
	Username        string
	DiscordUsername pgtype.Text
	PasswordHash    string
}
